def taille_mot(mot):
    print(len(mot))

In [3]:
taille_mot('test')

4


In [1]:
import random

In [5]:
def getNumber(number):
    if number in range(1,5):
        print('The number is equal to ' + str(number))

random_number = random.randint(1,5)
getNumber(random_number)

The number is equal to 2


In [22]:
## guess the right number
random_number = random.randint(1,5)

def guess_number(number):
    if int(number) == random_number:
        print("Bravo, vous avez trouvé le bon nombre ! C'était bien " + str(number))
    else:
        print("Ce n'est pas le bon nombre, veuillez réessayer")
        print("Le bon nombre était " + str(random_number))
        
guess_number_user = input('Choississez un nombre entre 1 et 5 : ')
print('Vous avez choisit ' + str(guess_number_user))
guess_number(guess_number_user)

Choississez un nombre entre 1 et 5 : 3
Vous avez choisit 3
Ce n'est pas le bon nombre, veuillez réessayer
Le bon nombre était 4


In [8]:
def jeu_devine_nombre():
    essaie = 4
    ramdom_number = random.randint(1,5)

    while essaie > 0:

        guess_number_user = input("Choississez un nombre entre 1 et 5 : ")

        if int(guess_number_user) > ramdom_number:
            print("Votre nombre est trop grand")
            essaie = essaie - 1
            print("Il vous reste " + str(essaie) + " essaies")

        elif int(guess_number_user) < ramdom_number:
            print("Votre nombre est trop petit")
            essaie = essaie - 1
            print("Il vous reste " + str(essaie) + " essaies")

        if essaie == 0:
            print("Vous n'avez plus d'essaie, le bon nombre était " + str(ramdom_number))

        if int(guess_number_user) == ramdom_number:
            print("BRAVO VOUS AVEZ TROUVÉ")
            print("Il vous restait " + str(essaie) + " essaies avant la fin du jeu")
            break

In [9]:
def reverse_string(string):
    return string[::-1]
my_string = "C'est le confinement"
reverse_string(my_string)

"tnemenifnoc el tse'C"

In [12]:
def calcul_carre(nombre):
    return nombre**2
calcul_carre(23)

529

In [13]:
def calcul_air_cercle(radius):
    return 2*3.1415*radius
calcul_air_cercle(20)

125.66000000000001

In [14]:
string_repalce = "ceci est un exemple de phrase"
def remplace_str(string):
    final_version = string.replace("e", "a")
    return final_version
remplace_str(string_repalce)

'caci ast un axampla da phrasa'

In [15]:
ma_liste = []
type(ma_liste)

list

In [13]:
big_list = ["gterh", "hvfjes", "fkjepzoghu", 1, 2, 3, 4, 5, True]
str_list = []
int_list = []
bool_list = []
print(type(big_list[-1]))

for elt in big_list:
    if type(elt) == str:
        str_list.append(elt)
    elif type(elt) == int:
        int_list.append(elt)
    elif type(elt) == bool:
        bool_list.append(elt)

print(str_list)
print(int_list)
print(bool_list)

<class 'bool'>
['gterh', 'hvfjes', 'fkjepzoghu']
[1, 2, 3, 4, 5]
[True]


In [14]:
big_big_list = big_list + str_list + int_list
print(big_big_list)

['gterh', 'hvfjes', 'fkjepzoghu', 1, 2, 3, 4, 5, True, 'gterh', 'hvfjes', 'fkjepzoghu', 1, 2, 3, 4, 5]


In [16]:
big_big_list.remove()

In [17]:
print(big_big_list)

['gterh', 'hvfjes', 'fkjepzoghu', 2, 3, 4, 5, True, 'gterh', 'hvfjes', 'fkjepzoghu', 1, 2, 3, 4, 5]


In [22]:
big_big_list.insert(0, 'test')
big_big_list.insert(-1, 'test')
big_big_list.append('test')

['test', 'test', 'test', 'gterh', 'hvfjes', 'fkjepzoghu', 2, 3, 4, 5, True, 'gterh', 'hvfjes', 'fkjepzoghu', 1, 2, 3, 4, 'test', 'test', 5, 'test', 'test', 'test']


In [27]:
big_big_list.remove('test')
print(big_big_list)

['gterh', 'hvfjes', 'fkjepzoghu', 2, 3, 4, 5, True, 'gterh', 'hvfjes', 'fkjepzoghu', 1, 2, 3, 4, 5, 'test', 'test', 'test']


In [29]:
mon_tuple = ()
print(type(mon_tuple))

<class 'tuple'>


In [4]:
mon_dico = {1: 'a', 2: 'b'}
for value in mon_dico.values():
    print(value)

a
b


In [9]:
dico_2 = {k:v*2 for k,v in mon_dico.items()}
dico_2 = {k*2 for k in mon_dico.keys()}

In [10]:
dico_2

{2, 4}

In [11]:
import os

In [26]:
file = open("file.txt", "r")
contenu = file.read()
print(contenu)
file.close()

ceci est un test d'ecriture dans un fichier txt crée en python


In [31]:
file = open("file.txt", "a")
file.write("\nBonjour")
file.close()

In [32]:
file = open("file.txt", "r")
contenu = file.read()
print(contenu)
file.close()

ceci est un test d'ecriture dans un fichier txt crée en python
Bonjour
Bonjour
Bonjour
Bonjour
Bonjour
Bonjour


In [36]:
with open("file.txt", "r") as fichier:
    lecture = fichier.read()
    print(lecture)
    fichier.close()

ceci est un test d'ecriture dans un fichier txt crée en python
Bonjour
Bonjour
Bonjour
Bonjour
Bonjour
Bonjour


In [37]:
with open('file.txt', 'a') as fichier:
    fichier.write("\nTest d'ajout")
    fichier.close()

In [38]:
with open("file.txt", "r") as fichier:
    lecture = fichier.read()
    print(lecture)
    fichier.close()

ceci est un test d'ecriture dans un fichier txt crée en python
Bonjour
Bonjour
Bonjour
Bonjour
Bonjour
Bonjour
Test d'ajout


In [39]:
create_text = input("Entrez le nom du fichier text à créer : ")
text_create_text = input("Ecrivez quelque chose : ")
with open(create_text + "txt", "w") as fichier:
    fichier.write(text_create_text)
    fichier.close()
with open(create_text, "r") as fichier:
    lecture = fichier.read()
    print(lecture)
    fichier.close()

Entrez le nom du fichier text à créer : python
Ecrivez quelque chose : ceci est un test 
ceci est un test 


In [3]:
a, b = 3, 4
c = 0
try:
    
    d = a/c
    print(d)
except: 
    print('Impossible de diviser par 0!')

Impossible de diviser par 0!


In [4]:
mon_dico = {1: 'test', 2: 'etdfey'}
{element for element in mon_dico}

{1, 2}

In [7]:
liste1 = [1, 2, 3]
liste1.append(8)
liste2 = liste1
liste2.append(19)
print(liste1)

[1, 2, 3, 8, 19]


In [ ]:
class Eleve:
    compteur = 0
    def __init__(self, nom, prenom, age, classe):
        self.nom = nom
        self.prenom = prenom
        self.age = age
        self.classe = classe
        Eleve.compteur += 1
    def presentation_eleve(self):
        print("Voici les informations sur l'élèves que vous avez demandé : " + self.nom + " " + self.prenom + ", " + self.age + ", " + self.classe)
    def Compteur(self):
        print("Il y a " + str(self.compteur) + " élèves!")
    def _get_lieu(self):
        return self._lieu
        

while True:
    question = input("Entrez une option : ")
    if question == "q":
        break
    elif question == "add":
        nom = input("Entrez un nom : ")
        prenom = input("Entrez un prenom : ")
        age = input("Entrez un age : ")
        classe = input("Entrez une classe : ")
        eleve = Eleve(nom, prenom, age, classe)
    elif question == "display":
        eleve.presentation_eleve()
    elif question == "compteur":
        eleve.Compteur()
    
"""premier_eleve = Eleve("Enzo", "Gros", "23", "Master II")
print(premier_eleve.presentation_eleve())
print(premier_eleve.Compteur())

deuxieme_eleve = Eleve("Gauthier", "Paturel", "24", "Master I")
print(deuxieme_eleve.presentation_eleve())
print(deuxieme_eleve.Compteur())"""

ENtrez une option : compteur
Il y a 3 élèves!
ENtrez une option : display
Voici les informations sur l'élèves que vous avez demandé : enzo gros, 23, Master II


In [1]:
import datetime

In [2]:
print(dir(datetime))

['MAXYEAR', 'MINYEAR', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'date', 'datetime', 'datetime_CAPI', 'sys', 'time', 'timedelta', 'timezone', 'tzinfo']


In [3]:
dir()

['In',
 'Out',
 '_',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i2',
 '_i3',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'datetime',
 'exit',
 'get_ipython',
 'quit']

In [4]:
a = 2019
b = 12
c = 21
date = datetime.date(a,b,c)
print(date)

2019-12-21


In [5]:
import re

In [6]:
#Numpy
import numpy

In [3]:
new_arr = numpy.array([[1,2,3], [2,3,4]])
print(new_arr.ndim)
print('second element of the second dimension list is : ' + str(new_arr[1, 1]))

2
second element of the second dimension list is : 3


In [4]:
my_arr = numpy.array([[[1,2,3], [2,34,45]], [[11,222,321], ["test","kfmneoruqbvm",45]]])
print(my_arr.ndim)
print('first element of the third dimension : ' + my_arr[1, -1, -1]) #dernire élément du dernier tableau

3
first element of the third dimension : 45


In [14]:
second_arr = numpy.array([1,2,3,4,5])
print(second_arr[1:-1])
print(second_arr[0:4:2])
print(second_arr[2:])
print(second_arr[:4])
print(second_arr[-3:-1])
print(second_arr[::2])

[2 3 4]
[1 3]
[3 4 5]
[1 2 3 4]
[3 4]
[1 3 5]


In [31]:
other_arr = numpy.array([[1,2,3], 
                         [3,4,5],
                         ["gfeo", "nfjiezg", "fekzom"]])
print(other_arr[1, 0::-1])
print(other_arr[0:3, 2])
                #i  #j
#i = la ligne sélectionnée
#j = la colonne sélectionnée
#other_arr[0:3, 2] ==> On prend à partir du premier élément, on prend 3 éléments, on sélectionne la troisième 
#colonne(n+1) => 2 + 1
#POUR LES TABLEAUX À 2 DIMENSIONS

#a2 = np.array([[10, 11, 12, 13, 14],
               #[15, 16, 17, 18, 19],
               #[20, 21, 22, 23, 24],
               #[25, 26, 27, 28, 29]])

#print(a2[1:,2:4])  # [[17 18]
                   #  [22 23]
                   #  [27 28]]

['3']
['3' '5' 'fekzom']


In [2]:
import numpy as np
a3 = np.array([[[10, 11, 12], 
                [13, 14, 15], 
                [16, 17, 18]],[[20, 21, 22], 
                               [23, 24, 25], 
                               [26, 27, 28]],
                                           [[30, 31, 32], 
                                            [33, 34, 35], 
                                            [36, 37, 38]]])
#A 3D array is like a stack of matrices:
#The first index, i, selects the matrix
#The second index, j, selects the row
#The third index, k, selects the column
######print(a3[2, 0, 1]) # 31#######
#print(a3[0, :, 1]) # [11 14 17]
#print(a3[:, 1, 2]) # [15, 25, 35]
#print(a3[2]) # [[30 31 32]
              #  [33 34 35]
              #  [36 37 38]]

In [2]:
class heros():
    def __init__(self, nom, taille, poids):
        self.nom = nom
        self.taille = taille
        self.poids = poids
    def print_heros():
        print("Voici les stats de votre heros : " + self.nom + " "+ self.taille + " "+ self.poids)

In [11]:
wrapper = 100

def price_string(func):
    def wrapper(arg):
        return "£" + str(func(arg))

    return wrapper  

@price_string
def new_price(arg):
    return float(wrapper * (90/100))

new_price(100)

'£90.0'

In [26]:
class carte():
    
    def __init__(self, nom, attaque, defense, attribut, classe, effet):
        self.nom = nom
        self.attaque = attaque
        self.defense = defense
        self.attribut = attribut
        self.classe = classe
        self.effet = effet
        
    def presentation(self):
        print("voici les informations sur les propriétés d'une carte : ")
        print("Nom : "+self.nom)
        print("Attaque : " + self.attaque)
        print("Défense : "+ self.defense)
        print("Attribut : "+ self.attribut)
        print("Classe : "+ self.classe)
        print("Effet : "+ self.effet)
        
Ra = carte("Dragon ailé de râ", "?", "?", "Divin", "Bête sacrée", "Need 3 sacrifices")
Ra.presentation()

voici les informations sur les propriétés d'une carte : 
Nom : Dragon ailé de râ
Attaque : ?
Défense : ?
Attribut : Divin
Classe : Bête sacrée
Effet : Need 3 sacrifices
